/**
 * Normalize column header names to handle typos and trailing spaces.
 */
export function normalizeHeader(header: string): string {
  const h = header.trim();
  const map: Record<string, string> = {
    'status ': 'Status',
    'status': 'Status',
    'emial': 'Email',
    'email': 'Email',
    'e-mail': 'Email',
    'region ': 'Region',
    'region': 'Region',
    'country ': 'Country',
    'country': 'Country',
    'activity ': 'Activity',
    'activity': 'Activity',
    'description ': 'Description',
    'description': 'Description',
    'focal point': 'Focal Point',
    'focal point ': 'Focal Point',
    'focalpoint': 'Focal Point',
    'budget ': 'Budget',
    'budget': 'Budget',
    'timeline ': 'Timeline',
    'timeline': 'Timeline',
    'name ': 'Name',
    'name': 'Name',
    'location ': 'Location',
    'location': 'Location',
    'title ': 'Title',
    'title': 'Title',
    'organization ': 'Organization',
    'organization': 'Organization',
    'expertise ': 'Expertise',
    'expertise': 'Expertise',
    'notes ': 'Notes',
    'notes': 'Notes',
    'type ': 'Type',
    'type': 'Type',
    'link ': 'Link',
    'link': 'Link',
    'url ': 'URL',
    'url': 'URL',
    'date ': 'Date',
    'date': 'Date',
    'contact ': 'Contact',
    'contact': 'Contact',
    'phone ': 'Phone',
    'phone': 'Phone',
    'category ': 'Category',
    'category': 'Category',
    'format ': 'Format',
    'format': 'Format',
    'language ': 'Language',
    'language': 'Language',
    'owner ': 'Owner',
    'owner': 'Owner',
    'priority ': 'Priority',
    'priority': 'Priority',
    'input ': 'Input',
    'input': 'Input',
    'output ': 'Output',
    'output': 'Output',
    'comments ': 'Comments',
    'comments': 'Comments',
    'target audiance': 'Target Audience',
    'type of asset': 'Type of Asset',
  };
  const lower = h.toLowerCase();
  return map[lower] ?? h;
}
